### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by justmert** [tonyukukkula/OktayBabaBot#4]
https://github.com/tonyukukkula/OktayBabaBot/blob/e1f021c92186393d1f1e04bfe840fe9afa463d3e/src/admin.json#L6

Nice security

**Comment by tonyukukkula** [comment]
Mert ilgine teşekkür ederim. Burada güvenliğin kendisi kendini bota tanımlatan kullanıcının kendisi :) tabi js dosyaları içinden şifreyi değiştirmeden yayına alan topluluklarda basit bir zor-kuvvet(brute force) saldırısı ile admin yetkileri alınabilir :D. Bunun için bot çalışmadan önce kendi "user id"leriyle botu çalıştırıp admin kayıt fonksiyonu devre dışı bırakılabilir ya da kolayca* adam akıllı bir şifre belirlenebilir.
